#!/usr/bin/env bash
# This script transfers file from client to server

if [ "$#" -lt 3 ]; then
	echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
file_path="$1"
server_ip="$2"
username="$3"
ssh_key_path="$4"
elif [ "$#" -lt 4 ]; then
	scp -o StrictHostKeyChecking=no "$file_path" "$username@$server_ip":~/
else
	scp -o StrictHostKeyChecking=no -i "$ssh_key_path" "$file_path" "$username@$server_ip":~/
fi
