#!/usr/bin/env bash
# configures nginx to redirect to another page
sudo apt-get -y update
sudo apt-get -y install nginx

mkdir /etc/nginx/html
touch /etc/nginx/html/index.html
echo "Hello World" > /etc/nginx/html/index.html

sed -i "s|location / {|location /redirect_me {|g"  /etc/nginx/sites-available/default
sed -i "s|try_files \$uri \$uri/ =404;|return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4; |g" /etc/nginx/sites-available/default

# Restart Nginx to apply changes
service nginx restart
