#!/usr/bin/env bash
# Configures Nginx with a custom 404 page that contains the string 'Ceci n'est pas une page'

# Update package information
sudo apt-get -y update

# Install Nginx
sudo apt-get -y install nginx

sudo mkdir /etc/nginx/html
sudo touch /etc/nginx/html/index.html

# Create the index.html file
echo "Hello World!" > /etc/nginx/html/index.html

sudo touch /etc/nginx/html/404.html

echo "Ceci n'est pas une page" > /etc/nginx/html/404.html

printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    root    /etc/nginx/html;
    index   index.html index.htm;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
    error_page 404 /404.html;
    location = /404 {
        root /etc/nginx/html;
        internal;
    }
}" > /etc/nginx/sites-available/default

# Restart Nginx to apply changes
sudo service nginx restart