#!/usr/bin/env bash
# Configures Nginx on a new ubuntu machine with a Custom HTTP Response Header

# Get the hostname
hostname=$(hostname)

#update and install nginx
sudo apt-get -y update
sudo apt-get -y install nginx

sudo mkdir /etc/nginx/html
touch /etc/nginx/html/index.html

echo "Hello World!" > /etc/nginx/html/index.html

sudo touch /etc/nginx/html/404.html
echo "Ceci n'est pas une page" > /etc/nginx/html/404.html

# Configure Nginx with custom response header
printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    root    /etc/nginx/html;
    index   index.html index.htm;

    # Custom HTTP response header
    add_header X-Served-By $hostname;

    error_page 404 /404.html;
    location = /404 {
        root /etc/nginx/html;
        internal;
    }
}" > /etc/nginx/sites-available/default

# Restart Nginx to apply changes
sudo service nginx restart
