#!/usr/bin/env bash
# This script installs and configure HAproxy on my lb-01 server
# so that it sends traffic to both web_01 and web_02
# It distributes requests using a roundrobin algorithm
# And it also ensures that HAproxy can be managed using init script

sudo apt-get -y update
sudo apt-get -y install haproxy

server_config=\
"
frontend http_front
    bind *:80
    stats uri /haproxy?stats
    default_backend http_back

backend http_back
    balance roundrobin
    server web-01 100.25.220.49:80 check
    server web-02 18.206.192.41:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# ensure haproxy can be managed via init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
